export const properties = [
  {
    id: 1,
    title: "Modern Luxury Villa",
    location: "Gurgaon",
    category: "Farm",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
    price: "₹ 1,25,00,000",
    priceValue: 12500000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 4000,
    description: "",
    yearBuilt: 2020,
    parking: 2,
    elevator: true,
    wifi: true,
    pool: true,
    gym: true,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1234" },
      { icon: "fa-house", label: "Type", value: "Villa" },
      { icon: "fa-door-open", label: "Room", value: "6" },
      { icon: "fa-bed", label: "Bedroom", value: "4" },
      { icon: "fa-bath", label: "Bath", value: "3" },
      { icon: "fa-seedling", label: "Big Yard", value: "1" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "4000" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "Yes" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2020" },
    ],
    amenities: [
      "Airconditioning", "Barbeque", "24x7 Security", "Jacuzzi", "Gym", 
      "Home Theater", "Balcony", "Recreation", "Indoor Game", "Modern Kitchen",
      "Walk-in Closet", "Wine Cellar", "Garage", "Microwave", "Pool",
      "Refrigerator", "Yard", "Skylight", "Landscaping", "Basketball"
    ],
    nearbyLocations: [
      { name: "HDFC Bank", dist: "500m", icon: "fa-building-columns", color: "#3b82f6" },
      { name: "City Hospital", dist: "1.2km", icon: "fa-hospital", color: "#ef4444" },
      { name: "Green Park", dist: "300m", icon: "fa-tree", color: "#22c55e" },
      { name: "St. Xavier School", dist: "800m", icon: "fa-school", color: "#f59e0b" },
    ]
  },
  {
    id: 2,
    title: "Premium City Apartment",
    location: "Sonipat",
    category: "Apartment",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80",
    price: "₹ 85,00,000",
    priceValue: 8500000,
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    description: "Experience luxury city living in this premium apartment. With modern amenities, stunning views, and a prime location in the heart of Noida, this property offers the perfect blend of comfort and convenience.",
    yearBuilt: 2019,
    parking: 1,
    elevator: true,
    wifi: true,
    pool: false,
    gym: true,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1235" },
      { icon: "fa-house", label: "Type", value: "Apartment" },
      { icon: "fa-door-open", label: "Room", value: "5" },
      { icon: "fa-bed", label: "Bedroom", value: "3" },
      { icon: "fa-bath", label: "Bath", value: "2" },
      { icon: "fa-seedling", label: "Big Yard", value: "0" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "1800" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "Yes" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2019" },
    ],
    amenities: [
      "Airconditioning", "24x7 Security", "Gym", "Balcony", "Modern Kitchen",
      "Walk-in Closet", "Garage", "Wifi", "Parking", "Elevator"
    ],
    nearbyLocations: [
      { name: "Metro Station", dist: "200m", icon: "fa-train", color: "#8b5cf6" },
      { name: "Shopping Mall", dist: "500m", icon: "fa-shopping-mall", color: "#ec4899" },
      { name: "City Park", dist: "400m", icon: "fa-tree", color: "#22c55e" },
      { name: "International School", dist: "1km", icon: "fa-school", color: "#f59e0b" },
    ]
  },
  {
    id: 3,
    title: "Luxury Pool Villa",
    location: "Delhi",
    category: "Commercial",
    image: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&auto=format&fit=crop&q=80",
    price: "₹ 2,10,00,000",
    priceValue: 21000000,
    type: "Villa",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 5500,
    description: "This magnificent Luxury Pool Villa in Jaipur offers an unparalleled lifestyle. Featuring a private pool, landscaped gardens, and opulent interiors, this property is perfect for those seeking the finest in royal living.",
    yearBuilt: 2021,
    parking: 3,
    elevator: false,
    wifi: true,
    pool: true,
    gym: true,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1236" },
      { icon: "fa-house", label: "Type", value: "Villa" },
      { icon: "fa-door-open", label: "Room", value: "8" },
      { icon: "fa-bed", label: "Bedroom", value: "5" },
      { icon: "fa-bath", label: "Bath", value: "4" },
      { icon: "fa-seedling", label: "Big Yard", value: "1" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "5500" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "No" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2021" },
    ],
    amenities: [
      "Airconditioning", "Barbeque", "24x7 Security", "Jacuzzi", "Gym", 
      "Home Theater", "Balcony", "Recreation", "Indoor Game", "Modern Kitchen",
      "Walk-in Closet", "Wine Cellar", "Garage", "Pool", "Patio"
    ],
    nearbyLocations: [
      { name: "Royal Golf Club", dist: "1km", icon: "fa-frog", color: "#10b981" },
      { name: "City Hospital", dist: "2km", icon: "fa-hospital", color: "#ef4444" },
      { name: "City Palace", dist: "5km", icon: "fa-landmark", color: "#f59e0b" },
      { name: "International Airport", dist: "12km", icon: "fa-plane", color: "#3b82f6" },
    ]
  },
  {
    id: 4,
    title: "Contemporary Family Home",
    location: "Delhi",
    category: "Land Or Plot",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&auto=format&fit=crop&q=80",
    price: "₹ 95,00,000",
    priceValue: 9500000,
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2200,
    description: "A beautiful contemporary family home in the planned city of Chandigarh. This property offers spacious living areas, modern amenities, and a peaceful neighborhood perfect for families.",
    yearBuilt: 2018,
    parking: 1,
    elevator: false,
    wifi: true,
    pool: false,
    gym: false,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1237" },
      { icon: "fa-house", label: "Type", value: "House" },
      { icon: "fa-door-open", label: "Room", value: "5" },
      { icon: "fa-bed", label: "Bedroom", value: "3" },
      { icon: "fa-bath", label: "Bath", value: "2" },
      { icon: "fa-seedling", label: "Big Yard", value: "1" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "2200" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "No" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2018" },
    ],
    amenities: [
      "Airconditioning", "24x7 Security", "Balcony", "Modern Kitchen", 
      "Garage", "Wifi", "Parking", "Patio", "Yard"
    ],
    nearbyLocations: [
      { name: "Government Hospital", dist: "800m", icon: "fa-hospital", color: "#ef4444" },
      { name: "Sector 17 Market", dist: "1.5km", icon: "fa-shopping-mall", color: "#ec4899" },
      { name: "Sukhna Lake", dist: "3km", icon: "fa-water", color: "#06b6d4" },
      { name: "St. Stephen's School", dist: "1km", icon: "fa-school", color: "#f59e0b" },
    ]
  },
  {
    id: 5,
    title: "Elegant Farm House",
    location: "Gurgaon",
    category: "Farm",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&auto=format&fit=crop&q=80",
    price: "₹ 1,75,00,000",
    priceValue: 17500000,
    type: "Farm House",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 6000,
    description: "Escape to this elegant farm house surrounded by lush greenery. Perfect for those seeking a peaceful retreat away from city chaos while maintaining accessibility to Gurgaon and Delhi.",
    yearBuilt: 2017,
    parking: 4,
    elevator: false,
    wifi: true,
    pool: true,
    gym: true,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1238" },
      { icon: "fa-house", label: "Type", value: "Farm House" },
      { icon: "fa-door-open", label: "Room", value: "10" },
      { icon: "fa-bed", label: "Bedroom", value: "5" },
      { icon: "fa-bath", label: "Bath", value: "4" },
      { icon: "fa-seedling", label: "Big Yard", value: "2" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "6000" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "No" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2017" },
    ],
    amenities: [
      "Airconditioning", "Barbeque", "24x7 Security", "Jacuzzi", "Gym", 
      "Balcony", "Recreation", "Indoor Game", "Modern Kitchen",
      "Walk-in Closet", "Garage", "Pool", "Yard", "Landscaping"
    ],
    nearbyLocations: [
      { name: "IMT Manesar", dist: "3km", icon: "fa-building", color: "#6366f1" },
      { name: "Fortis Hospital", dist: "5km", icon: "fa-hospital", color: "#ef4444" },
      { name: "Heritage Village", dist: "4km", icon: "fa-landmark", color: "#f59e0b" },
      { name: "Damdama Lake", dist: "8km", icon: "fa-water", color: "#06b6d4" },
    ]
  },
  {
    id: 6,
    title: "Skyline View Apartment",
    location: "Sonipat",
    category: "Apartment",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&auto=format&fit=crop&q=80",
    price: "₹ 1,10,00,000",
    priceValue: 11000000,
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    description: "Stunning apartment with breathtaking skyline views in the heart of Mumbai. Modern design, premium amenities, and proximity to business districts make this an excellent investment.",
    yearBuilt: 2022,
    parking: 1,
    elevator: true,
    wifi: true,
    pool: true,
    gym: true,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1239" },
      { icon: "fa-house", label: "Type", value: "Apartment" },
      { icon: "fa-door-open", label: "Room", value: "4" },
      { icon: "fa-bed", label: "Bedroom", value: "2" },
      { icon: "fa-bath", label: "Bath", value: "2" },
      { icon: "fa-seedling", label: "Big Yard", value: "0" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "1200" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "Yes" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2022" },
    ],
    amenities: [
      "Airconditioning", "24x7 Security", "Gym", "Balcony", "Modern Kitchen",
      "Walk-in Closet", "Garage", "Wifi", "Parking", "Elevator", "Pool"
    ],
    nearbyLocations: [
      { name: "Bandra Station", dist: "500m", icon: "fa-train", color: "#8b5cf6" },
      { name: "Lilavati Hospital", dist: "1km", icon: "fa-hospital", color: "#ef4444" },
      { name: "Juhu Beach", dist: "2km", icon: "fa-umbrella-beach", color: "#f59e0b" },
      { name: "Shopping Plaza", dist: "300m", icon: "fa-shopping-mall", color: "#ec4899" },
    ]
  },
  {
    id: 7,
    title: "Beach Side Villa",
    location: "Rohtak",
    category: "Commercial",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&auto=format&fit=crop&q=80",
    price: "₹ 3,50,00,000",
    priceValue: 35000000,
    type: "Villa",
    bedrooms: 6,
    bathrooms: 5,
    sqft: 7000,
    description: "Luxurious beach side villa in Goa with direct beach access. This exotic property features modern architecture blended with coastal vibes, perfect for those seeking a tropical paradise.",
    yearBuilt: 2020,
    parking: 3,
    elevator: false,
    wifi: true,
    pool: true,
    gym: true,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1240" },
      { icon: "fa-house", label: "Type", value: "Villa" },
      { icon: "fa-door-open", label: "Room", value: "12" },
      { icon: "fa-bed", label: "Bedroom", value: "6" },
      { icon: "fa-bath", label: "Bath", value: "5" },
      { icon: "fa-seedling", label: "Big Yard", value: "1" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "7000" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "No" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2020" },
    ],
    amenities: [
      "Airconditioning", "Barbeque", "24x7 Security", "Jacuzzi", "Gym", 
      "Home Theater", "Balcony", "Recreation", "Indoor Game", "Modern Kitchen",
      "Walk-in Closet", "Wine Cellar", "Garage", "Pool", "Patio"
    ],
    nearbyLocations: [
      { name: "Dabolim Airport", dist: "25km", icon: "fa-plane", color: "#3b82f6" },
      { name: "Benaulim Beach", dist: "200m", icon: "fa-umbrella-beach", color: "#f59e0b" },
      { name: "Medical Hospital", dist: "3km", icon: "fa-hospital", color: "#ef4444" },
      { name: "Casino", dist: "8km", icon: "fa-dice", color: "#8b5cf6" },
    ]
  },
  {
    id: 8,
    title: "Classic Duplex House",
    location: "Sonipat",
    category: "Land Or Plot",
    image: "https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800&auto=format&fit=crop&q=80",
    price: "₹ 78,00,000",
    priceValue: 7800000,
    type: "Duplex",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    description: "Classic duplex house in Lucknow with traditional architecture and modern amenities. Spacious living areas, attached terraces, and a prime location in a peaceful residential colony.",
    yearBuilt: 2016,
    parking: 2,
    elevator: false,
    wifi: true,
    pool: false,
    gym: false,
    highlights: [
      { icon: "fa-tag", label: "ID NO.", value: "#1241" },
      { icon: "fa-house", label: "Type", value: "Duplex" },
      { icon: "fa-door-open", label: "Room", value: "7" },
      { icon: "fa-bed", label: "Bedroom", value: "4" },
      { icon: "fa-bath", label: "Bath", value: "3" },
      { icon: "fa-seedling", label: "Big Yard", value: "1" },
      { icon: "fa-house-circle-check", label: "Purpose", value: "For Sale" },
      { icon: "fa-ruler-combined", label: "Sqft", value: "2800" },
      { icon: "fa-car", label: "Parking", value: "Yes" },
      { icon: "fa-elevator", label: "Elevator", value: "No" },
      { icon: "fa-wifi", label: "Wifi", value: "Yes" },
      { icon: "fa-calendar-days", label: "Built in", value: "2016" },
    ],
    amenities: [
      "Airconditioning", "24x7 Security", "Balcony", "Modern Kitchen", 
      "Walk-in Closet", "Garage", "Wifi", "Parking", "Patio", "Yard"
    ],
    nearbyLocations: [
      { name: "Lucknow University", dist: "2km", icon: "fa-graduation-cap", color: "#7c3aed" },
      { name: "Civil Hospital", dist: "1.5km", icon: "fa-hospital", color: "#ef4444" },
      { name: "Hazratganj Market", dist: "3km", icon: "fa-shopping-mall", color: "#ec4899" },
      { name: "Ambedkar Park", dist: "500m", icon: "fa-tree", color: "#22c55e" },
    ]
  },
];
